/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bookcaseOpen.glb --output src/components/models/BookcaseOpen.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BookcaseOpen(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/bookcaseOpen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bookcaseOpen(Clone)'].geometry} material={materials.wood} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/bullseye/models/bookcaseOpen.glb')
