/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chairDesk.glb --output src/components/models/ChairDesk.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ChairDesk(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/chairDesk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['chairDesk(Clone)'].geometry} material={materials.metalMedium} castShadow receiveShadow>
        <group position={[0.167, 0.19, -0.16]}>
          <mesh geometry={nodes.Mesh_chair.geometry} material={materials.carpet} castShadow receiveShadow />
          <mesh geometry={nodes.Mesh_chair_1.geometry} material={materials.metalMedium} castShadow receiveShadow />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/bullseye/models/chairDesk.glb')
