/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computerScreen.glb --output src/components/models/ComputerScreen.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ComputerScreen(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/computerScreen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_computerScreen.geometry} material={materials.metalDark} castShadow receiveShadow />
      <mesh geometry={nodes.Mesh_computerScreen_1.geometry} material={materials.metal} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/bullseye/models/computerScreen.glb')
