/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk.glb --output src/components/models/Desk.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['desk(Clone)'].geometry} material={materials.wood} castShadow receiveShadow>
        <group position={[0.04, 0.274, -0.164]}>
          <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} castShadow receiveShadow />
          <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} castShadow receiveShadow />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/bullseye/models/desk.glb')
