/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lampRoundTable.glb --output src/components/models/LampRoundTable.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LampRoundTable(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/lampRoundTable.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_lampRoundTable.geometry} material={materials.metal} castShadow receiveShadow />
      <mesh geometry={nodes.Mesh_lampRoundTable_1.geometry} material={materials.lamp} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/bullseye/models/lampRoundTable.glb')
