/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/laptop.glb --output src/components/models/Laptop.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.44}>
        <mesh geometry={nodes.Mesh_laptop.geometry} material={materials.metalDark} castShadow receiveShadow />
        <mesh geometry={nodes.Mesh_laptop_1.geometry} material={materials.metal} castShadow receiveShadow />
        <mesh geometry={nodes.Mesh_laptop_2.geometry} material={materials.metalMedium} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/bullseye/models/laptop.glb')
