/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pottedPlant.glb --output src/components/models/PottedPlant.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PottedPlant(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/pottedPlant.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={2}>
        <mesh geometry={nodes.Mesh_pottedPlant.geometry} material={materials.wood} castShadow receiveShadow />
        <mesh geometry={nodes.Mesh_pottedPlant_1.geometry} material={materials.woodDark} castShadow receiveShadow />
        <mesh geometry={nodes.plant.geometry} material={materials.plant} position={[-0.053, 0.059, 0.06]} scale={0.5} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/bullseye/models/pottedPlant.glb')
