/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rugRectangle.glb --output src/components/models/RugRectangle.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RugRectangle(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/rugRectangle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_rugRectangle.geometry} material={materials.carpet} castShadow receiveShadow />
      <mesh geometry={nodes.Mesh_rugRectangle_1.geometry} material={materials.carpetDarker} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/bullseye/models/rugRectangle.glb')
