/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/trashcan.glb --output src/components/models/Trashcan.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Trashcan(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/trashcan.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]} scale={0.472}>
        <mesh geometry={nodes.Mesh_trashcan.geometry} material={materials.metal} castShadow receiveShadow />
        <mesh geometry={nodes.Mesh_trashcan_1.geometry} material={materials.metalDark} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/bullseye/models/trashcan.glb')
