/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wallWindow.glb --output src/components/models/WallWindow.jsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WallWindow(props) {
  const { nodes, materials } = useGLTF('/bullseye/models/wallWindow.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_wallWindow.geometry} material={materials.wood} castShadow receiveShadow />
      <mesh geometry={nodes.Mesh_wallWindow_1.geometry} material={materials.metalDark} castShadow receiveShadow />
      <mesh geometry={nodes.Mesh_wallWindow_2.geometry} material={materials._defaultMat} castShadow receiveShadow />
      <group position={[0.313, 0.393, -0.003]}>
        <mesh geometry={nodes.Mesh_window.geometry} material={materials.glass} castShadow receiveShadow />
        <mesh geometry={nodes.Mesh_window_1.geometry} material={materials.wood} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/bullseye/models/wallWindow.glb')
